name: Ecommerce Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest          # github  Use the latest Ubuntu runner

    steps:
      - name: Checkout code        # github  Checkout the repository
        uses: actions/checkout@v4  # github download your repo in VM

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test with Maven
        run: mvn clean test